[
    "Media",
    "Read our stories",
    "Get to know ASE by reading our top stories",
    "Read More",
    "Join us on our podcast",
    "Listen to mind opening discussions on our podcast where we dive into different topics about economics, research and other aspects",
    "Updates",
    "Get More Updates",
    "Undergraduate",
    "Postgraduate",
    "Our Campuses",
    "Nigeria",
    "ASE offers graduate and undergraduate courses at its campuses in Nigeria",
    "Benin Republic",
    "ASE offers graduate and undergraduate courses at its campuses in Benin",
    "Cote d'Ivoire",
    "ASE offers graduate and undergraduate courses at its campuses in Cote d'Ivoire",
    "The Hunter African School Program to Expand Representation in Economics (HASPERE) is a collaborative initiative between Hunter College and the African School of Economics to train and mentor talented Black and other underrepresented minority students.",
    "From the President: The ASE Vision",
    "Over",
    "students qualified for aid.",
    "Financial Aid",
    "Here is a list of scholarships and fee waviers on offer at ASE",
    "ASE in Numbers",
    "Students",
    "across our different campuses.",
    "Degree",
    "programs.",
    "Campuses",
    "across 2 continents.",
    "Our Partners",
]